name: Tests
on: [push, pull_request_target]

jobs:
  test:
    name: ${{ matrix.os }} (Node ${{ matrix.node-version }})
    runs-on: ${{ matrix.os }}
    # always run on push events
    # only run on pull_request_target event when pull request pulls from fork repository
    if: >
      github.event_name == 'push' || 
      github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository 
    strategy:
      fail-fast: false
      matrix:
        node-version: [6, 8, 9, 10, 11, 12, 13, 14]
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm audit --production

      - run: set -o pipefail && npm audit --audit-level=high --parseable | awk -F $'\t' 'NF {print $2,"("$3") - "$4" - "$5" - "$6}' | awk '!visited[$0]++'

      - run: npm test

      - run: npm run lint
